### ISSUE TITLE
loop_extract prefixing results in neverending prefixed filenames

### ISSUE THREAD

**Issue by kostrzewa** [kostrzewa/cvc_depgraph#15]
@pittlerf Unfortunately we need to modify loop_extract once more. The way the output filename is currently constructed means that if one filters filtered data, filtered is  prefixed twice. If one then filters it again, its prefixed thrice and so on.

I think we need settings for 

```
LoopExtract_OutputFilenamePrefix
```

and

```
LoopExtract_OutputFilenameSuffix
````

to construct user-configurable filenames...

ps: There is also still the outstanding issue of the text header not being modified by loop_extract. Even when just the scalar loop type is present, the header includes a description of all loop types. Note sure if we want to touch that one though just because it will be some effort...

**Comment by kostrzewa** [comment]
I guess this has top priority for today...

**Comment by pittlerf** [comment]
Yes, that has to be done. For the ps, I  think the analysis code does not use that info

**Comment by kostrzewa** [comment]
> For the ps, I think the analysis code does not use that info

only because it's not reliably available, in the beginning the idea was to use the meta-information
